version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.pro
    tty: true
    ports:
      - "80:80"
    depends_on:
      - database
    volumes:
      - $HOME/DOCKERHOME:/app/bookMarkLibrary/storage
    environment:
      - ENV=testing
      - DB_HOST=database
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql:/var/lib/mysql
      - $PWD/mysql-confd:/etc/mysql/conf.d
    env_file:
      - ./.env
