"""empty message

Revision ID: 6dc20e8b0fad
Revises: a6868254515a
Create Date: 2019-04-29 13:58:10.767359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dc20e8b0fad'
down_revision = 'a6868254515a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('bookmarks', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'deleted_at')
    op.alter_column('bookmarks', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('bookmarks', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
