"""empty message

Revision ID: 72e7fbebe44c
Revises: 84076d19692f
Create Date: 2019-05-05 14:05:47.558891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72e7fbebe44c'
down_revision = '84076d19692f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookmarks', 'url', new_column_name='_url',  existing_type=mysql.VARCHAR(length=255),
               nullable=False)


def downgrade():
    op.alter_column('bookmarks', '_url', new_column_name='url',  existing_type=mysql.VARCHAR(length=255),
               nullable=False)

