"""empty message

Revision ID: 92a3ddad3514
Revises: 72e7fbebe44c
Create Date: 2019-05-07 23:10:45.204363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92a3ddad3514'
down_revision = '72e7fbebe44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'name')
    # ### end Alembic commands ###
