"""empty message

Revision ID: ad42ec6ad206
Revises: 92a3ddad3514
Create Date: 2019-05-12 07:58:33.055532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy_utils import UUIDType
import uuid

# revision identifiers, used by Alembic.
revision = 'ad42ec6ad206'
down_revision = '92a3ddad3514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', UUIDType(binary=False), nullable=False, default=uuid),
                    sa.Column('tag', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('bookmark_tag_rel',
                    sa.Column('bookmarks', sa.Integer(), nullable=True),
                    sa.Column('tags', UUIDType(binary=False), nullable=False, default=uuid),
                    sa.ForeignKeyConstraint(['bookmarks'], ['bookmarks.id'], ),
                    sa.ForeignKeyConstraint(['tags'], ['tags.id'], )
                    )
    op.alter_column('bookmarks', 'parent_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.drop_index('com_id_idx', table_name='categories')
    op.drop_index('parent_id_idx', table_name='categories')
    op.drop_index('user_id_idx', table_name='categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id_idx', 'categories', ['created_at'], unique=False)
    op.create_index('parent_id_idx', 'categories', ['parent_id'], unique=False)
    op.create_index('com_id_idx', 'categories', ['parent_id', 'user_id'], unique=False)
    op.alter_column('bookmarks', 'parent_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.drop_table('bookmark_tag_rel')
    op.drop_table('tags')
    # ### end Alembic commands ###
