"""empty message

Revision ID: ad42ec6ad206
Revises: 92a3ddad3514
Create Date: 2019-05-12 07:58:33.055532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy_utils import UUIDType
import uuid

# revision identifiers, used by Alembic.
revision = 'ad42ec6ad206'
down_revision = '92a3ddad3514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', UUIDType(binary=False), nullable=False, default=uuid),
                    sa.Column('tag', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('bookmark_tag_rel',
                    sa.Column('bookmarks', sa.Integer(), nullable=True),
                    sa.Column('tags', UUIDType(binary=False), nullable=False, default=uuid),
                    sa.ForeignKeyConstraint(['bookmarks'], ['bookmarks.id'], ),
                    sa.ForeignKeyConstraint(['tags'], ['tags.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark_tag_rel')
    op.drop_table('tags')
    # ### end Alembic commands ###
