name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  promotionRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - name: Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get branch name
        id: get_branch
        run: echo "::set-output name=branch::${GITHUB_REF}"
      # - name: Reset release branch
      #   run: |
      #     git fetch origin master:master
      #     git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.get_branch.outputs.branch }}
          title: Release-${{ steps.date.outputs.date }}
          reviewers: |
            gring2