name: auto-merge dependabot

on:
  pull_request:
    branches:
      - master
    tags:
      - dependencies
    types:
      - opened
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.PAT }}